###############################################################################
# Endpoints
###############################################################################

output "fqdn" {
  description = "Full DNS name of the storage host."
  value       = local.fqdn
}

output "garage_s3_endpoint" {
  description = "Garage S3 API endpoint (HTTP, port 3900). Use as Terraform S3 backend endpoint."
  value       = "http://${local.fqdn}:3900"
}

output "garage_admin_endpoint" {
  description = "Garage admin API endpoint (port 3903) — bucket/key management."
  value       = "http://${local.fqdn}:3903"
}

output "zot_endpoint" {
  description = "Zot OCI registry endpoint (HTTPS, port 5000). Use as registry_mirror.endpoint in the cluster stack."
  value       = "https://${local.fqdn}:5000"
}

###############################################################################
# Buckets
###############################################################################

output "garage_state_bucket" {
  description = "Bucket reserved for Terraform state."
  value       = var.garage_state_bucket
}

output "garage_oci_bucket" {
  description = "Bucket used by Zot for blob storage."
  value       = var.garage_oci_bucket
}

output "garage_buckets" {
  description = "All buckets created in Garage."
  value       = var.garage_buckets
}

###############################################################################
# Credentials (sensitive)
###############################################################################

output "garage_access_key_id" {
  description = "Garage S3 access key id ('terraform' account). Use in backend.s3.hcl access_key."
  value       = local.garage_access_key_id
  sensitive   = true
}

output "garage_secret_access_key" {
  description = "Garage S3 secret. Use in backend.s3.hcl secret_key."
  value       = local.garage_secret_access_key
  sensitive   = true
}

###############################################################################
# TLS material
###############################################################################

output "zot_ca_cert" {
  description = "Self-signed certificate for Zot. Pass to var.registry_mirror.ca_cert in the cluster stack if you prefer real TLS verification over insecure_skip_verify."
  value       = tls_self_signed_cert.zot.cert_pem
}

###############################################################################
# Snippets — paste into the cluster stack
###############################################################################

output "backend_s3_hcl" {
  description = "Ready-to-paste contents for the cluster stack's backend.s3.hcl. `terraform output -raw backend_s3_hcl > ../10-cluster/backend.s3.hcl`."
  value       = <<-EOT
    # Generated by modules/storage. Do not commit (it contains credentials).
    bucket                      = "${var.garage_state_bucket}"
    key                         = "${var.tfstate_key_prefix}/terraform.tfstate"
    endpoints                   = { s3 = "http://${local.fqdn}:3900" }
    access_key                  = "${local.garage_access_key_id}"
    secret_key                  = "${local.garage_secret_access_key}"
    region                      = "garage"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
    use_lockfile                = true
  EOT
  sensitive   = true
}

output "registry_mirror_tfvars_snippet" {
  description = "Ready-to-paste registry_mirror block for the cluster stack's credentials.auto.tfvars."
  value       = <<-EOT
    registry_mirror = {
      endpoint             = "https://${local.fqdn}:5000"
      insecure_skip_verify = true
    }
  EOT
}
